import {
  BarChart3Icon,
  Bell,
  Building2,
  CalculatorIcon,
  CreditCard,
  CreditCardIcon,
  FileIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
  Folder,
  Home,
  Paintbrush,
  SettingsIcon,
  Star,
  User,
  Users,
  UsersIcon,
  Wrench,
} from "lucide-react";
import type { MenuConfig } from "./nav.types";

export const menuConfig: MenuConfig = {
  main: [
    {
      group: 1,
      title: "navigation.group.general",
      items: [
        {
          tKey: "navigation.dashboard",
          name: "Dashboard",
          href: "/app",
          icon: Home,
          ability: "dashboard",
        },
        {
          tKey: "navigation.customers",
          name: "Customers",
          href: "/app/customers",
          icon: User,
          ability: "customer:view",
        },
        {
          tKey: "navigation.items",
          name: "Items",
          href: "/app/items",
          icon: Star,
          ability: "item:view",
        },
      ],
    },
    {
      group: 2,
      title: "navigation.group.sales",
      items: [
        {
          tKey: "navigation.estimates",
          name: "Estimates",
          href: "/app/estimates",
          icon: FileIcon,
          ability: "estimate:view",
        },
        {
          tKey: "navigation.invoices",
          name: "Invoices",
          href: "/app/invoices",
          icon: FileTextIcon,
          ability: "invoice:view",
          counterKey: "invoicesDue",
        },
        {
          tKey: "navigation.recurring_invoices",
          name: "Recurring",
          href: "/app/recurring-invoices",
          icon: FileSpreadsheetIcon,
          ability: "recurring-invoice:view",
        },
        {
          tKey: "navigation.payments",
          name: "Payments",
          href: "/app/payments",
          icon: CreditCardIcon,
          ability: "payment:view",
        },
        {
          tKey: "navigation.expenses",
          name: "Expenses",
          href: "/app/expenses",
          icon: CalculatorIcon,
          ability: "expense:view",
        },
      ],
    },
    {
      group: 3,
      title: "navigation.group.management",
      items: [
        {
          tKey: "navigation.users",
          name: "Users",
          href: "/app/users",
          icon: UsersIcon,
          ownerOnly: true,
          ability: "role:manage",
        },
        {
          tKey: "navigation.reports",
          name: "Reports",
          href: "/app/reports",
          icon: BarChart3Icon,
          ability: "report:financial:view",
          features: ["reports"],
        },
        {
          tKey: "navigation.settings",
          name: "Settings",
          href: "/app/settings",
          icon: SettingsIcon,
        },
      ],
    },
  ],
  settings: [
    {
      group: "org",
      title: "settings.group.organization",
      items: [
        {
          tKey: "settings.company",
          name: "Company",
          href: "/app/settings/company",
          icon: Building2,
          ownerOnly: true,
          ability: "settings:company:update",
        },
        {
          tKey: "settings.preferences",
          name: "Preferences",
          href: "/app/settings/preferences",
          icon: Wrench,
          ownerOnly: true,
        },
        {
          tKey: "settings.customization",
          name: "Customization",
          href: "/app/settings/customization",
          icon: Paintbrush,
          ownerOnly: true,
        },
        {
          tKey: "settings.roles",
          name: "Roles",
          href: "/app/settings/roles",
          icon: Users,
          ownerOnly: true,
          ability: "role:manage",
        },
        {
          tKey: "settings.tax_types",
          name: "Tax Types",
          href: "/app/settings/tax-types",
          icon: Folder,
          ability: "tax-type:view",
        },
        {
          tKey: "settings.payment_modes",
          name: "Payment Modes",
          href: "/app/settings/payment-modes",
          icon: CreditCard,
          ability: "payment-mode:view",
        },
        {
          tKey: "settings.custom_fields",
          name: "Custom Fields",
          href: "/app/settings/custom-fields",
          icon: Folder,
          ability: "custom-field:view",
        },
        {
          tKey: "settings.notes",
          name: "Notes",
          href: "/app/settings/notes",
          icon: Bell,
          ability: "note:view",
        },
      ],
    },
  ],
};
