import type { DbClient } from "@/server/db";
import { currencies } from "@/server/db/schemas";

const DEFAULT_CURRENCIES = [
  {
    name: "US Dollar",
    code: "USD",
    symbol: "$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "British Pound",
    code: "GBP",
    symbol: "£",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Euro",
    code: "EUR",
    symbol: "€",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: true,
  },
  {
    name: "South African Rand",
    code: "ZAR",
    symbol: "R",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Danish Krone",
    code: "DKK",
    symbol: "kr",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: true,
  },
  {
    name: "Israeli Shekel",
    code: "ILS",
    symbol: "NIS ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Swedish Krona",
    code: "SEK",
    symbol: "kr",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: true,
  },
  {
    name: "Kenyan Shilling",
    code: "KES",
    symbol: "KSh ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Kuwaiti Dinar",
    code: "KWD",
    symbol: "KWD ",
    precision: 3,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Canadian Dollar",
    code: "CAD",
    symbol: "C$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Philippine Peso",
    code: "PHP",
    symbol: "P ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Nepali Rupee",
    code: "NPR",
    symbol: "रू",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Indian Rupee",
    code: "INR",
    symbol: "₹",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Australian Dollar",
    code: "AUD",
    symbol: "$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Singapore Dollar",
    code: "SGD",
    symbol: "S$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Norske Kroner",
    code: "NOK",
    symbol: "kr",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: true,
  },
  {
    name: "New Zealand Dollar",
    code: "NZD",
    symbol: "$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Vietnamese Dong",
    code: "VND",
    symbol: "₫",
    precision: 0,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Swiss Franc",
    code: "CHF",
    symbol: "Fr.",
    precision: 2,
    thousandSeparator: "'",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Guatemalan Quetzal",
    code: "GTQ",
    symbol: "Q",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Malaysian Ringgit",
    code: "MYR",
    symbol: "RM",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Brazilian Real",
    code: "BRL",
    symbol: "R$",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Thai Baht",
    code: "THB",
    symbol: "฿",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Nigerian Naira",
    code: "NGN",
    symbol: "₦",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Argentine Peso",
    code: "ARS",
    symbol: "$",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Bangladeshi Taka",
    code: "BDT",
    symbol: "Tk",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "United Arab Emirates Dirham",
    code: "AED",
    symbol: "DH ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Hong Kong Dollar",
    code: "HKD",
    symbol: "HK$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Indonesian Rupiah",
    code: "IDR",
    symbol: "Rp",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Mexican Peso",
    code: "MXN",
    symbol: "$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Egyptian Pound",
    code: "EGP",
    symbol: "E£",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Colombian Peso",
    code: "COP",
    symbol: "$",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Central African Franc",
    code: "XAF",
    symbol: "CFA ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "West African Franc",
    code: "XOF",
    symbol: "CFA ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Chinese Renminbi",
    code: "CNY",
    symbol: "RMB ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Rwandan Franc",
    code: "RWF",
    symbol: "RF ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Tanzanian Shilling",
    code: "TZS",
    symbol: "TSh ",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Netherlands Antillean Guilder",
    code: "ANG",
    symbol: "NAƒ",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Trinidad and Tobago Dollar",
    code: "TTD",
    symbol: "TT$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "East Caribbean Dollar",
    code: "XCD",
    symbol: "EC$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Ghanaian Cedi",
    code: "GHS",
    symbol: "‎GH₵",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Bulgarian Lev",
    code: "BGN",
    symbol: "Лв.",
    precision: 2,
    thousandSeparator: " ",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Aruban Florin",
    code: "AWG",
    symbol: "Afl. ",
    precision: 2,
    thousandSeparator: " ",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Turkish Lira",
    code: "TRY",
    symbol: "TL ",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Romanian New Leu",
    code: "RON",
    symbol: "RON",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Croatian Kuna",
    code: "HRK",
    symbol: "kn",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Saudi Riyal",
    code: "SAR",
    symbol: "‎SِAR",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Japanese Yen",
    code: "JPY",
    symbol: "¥",
    precision: 0,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Maldivian Rufiyaa",
    code: "MVR",
    symbol: "Rf",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Costa Rican Colón",
    code: "CRC",
    symbol: "₡",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Pakistani Rupee",
    code: "PKR",
    symbol: "Rs ",
    precision: 0,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Polish Zloty",
    code: "PLN",
    symbol: "zł",
    precision: 2,
    thousandSeparator: " ",
    decimalSeparator: ",",
    swapCurrencySymbol: true,
  },
  {
    name: "Sri Lankan Rupee",
    code: "LKR",
    symbol: "LKR",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: true,
  },
  {
    name: "Czech Koruna",
    code: "CZK",
    symbol: "Kč",
    precision: 2,
    thousandSeparator: " ",
    decimalSeparator: ",",
    swapCurrencySymbol: true,
  },
  {
    name: "Uruguayan Peso",
    code: "UYU",
    symbol: "$",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Namibian Dollar",
    code: "NAD",
    symbol: "$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Tunisian Dinar",
    code: "TND",
    symbol: "‎د.ت",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Russian Ruble",
    code: "RUB",
    symbol: "₽",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Mozambican Metical",
    code: "MZN",
    symbol: "MT",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: true,
  },
  {
    name: "Omani Rial",
    code: "OMR",
    symbol: "ر.ع.",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Ukrainian Hryvnia",
    code: "UAH",
    symbol: "₴",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Macanese Pataca",
    code: "MOP",
    symbol: "MOP$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Taiwan New Dollar",
    code: "TWD",
    symbol: "NT$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Dominican Peso",
    code: "DOP",
    symbol: "RD$",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Chilean Peso",
    code: "CLP",
    symbol: "$",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Serbian Dinar",
    code: "RSD",
    symbol: "RSD",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Kyrgyzstani Som",
    code: "KGS",
    symbol: "С̲ ",
    precision: 2,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: false,
  },
  {
    name: "Iraqi Dinar",
    code: "IQD",
    symbol: "ع.د",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Peruvian Soles",
    code: "PEN",
    symbol: "S/",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Moroccan Dirham",
    code: "MAD",
    symbol: "DH",
    precision: 2,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Jamaican Dollar",
    code: "JMD",
    symbol: "$",
    precision: 0,
    thousandSeparator: ",",
    decimalSeparator: ".",
    swapCurrencySymbol: false,
  },
  {
    name: "Macedonian Denar",
    code: "MKD",
    symbol: "ден",
    precision: 0,
    thousandSeparator: ".",
    decimalSeparator: ",",
    swapCurrencySymbol: true,
  },
] as const;

/**
 * Inserts the full global currency catalog when the table is empty.
 * Runs at most once per database — subsequent calls are no-ops.
 */
export async function ensureDefaultCurrencies(db: DbClient): Promise<void> {
  const existing = await db
    .select({ id: currencies.id })
    .from(currencies)
    .limit(1);
  if (existing.length > 0) return;

  await db.insert(currencies).values(
    DEFAULT_CURRENCIES.map((c) => ({
      name: c.name,
      code: c.code,
      symbol: c.symbol,
      precision: c.precision,
      thousandSeparator: c.thousandSeparator,
      decimalSeparator: c.decimalSeparator,
      swapCurrencySymbol: c.swapCurrencySymbol,
    })),
  );
}
